'use client';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Check, ChevronDown, ChevronUp, Eye, X, Download, ShoppingCart } from 'lucide-react';
import { useState, useEffect } from 'react';
import { useRouter } from "next/navigation";

export default function PricingPage() {
  const [loadingPlan, setLoadingPlan] = useState<string | null>(null);
  const [isLoggedIn, setIsLoggedIn] = useState<boolean>(false);
  const [userEmail, setUserEmail] = useState<string | null>(null);
  const [receiptPreview, setReceiptPreview] = useState<string | null>(null);
  const [showPreview, setShowPreview] = useState<boolean>(false);
  const [receiptData, setReceiptData] = useState<any>(null);
  const router = useRouter();

  useEffect(() => {
    // Check authentication status on component mount
    const checkAuth = () => {
      try {
        const userData = localStorage.getItem("user");
        const user = userData ? JSON.parse(userData) : null;
        const email = user?.email;
        
        setIsLoggedIn(!!email);
        setUserEmail(email);
      } catch (error) {
        console.error('Error checking auth:', error);
        setIsLoggedIn(false);
        setUserEmail(null);
      }
    };

    checkAuth();
    
    // Listen for storage changes (login/logout in other tabs)
    window.addEventListener('storage', checkAuth);
    
    return () => {
      window.removeEventListener('storage', checkAuth);
    };
  }, []);

  // Load receipt preview from localStorage
  useEffect(() => {
    const loadReceiptPreview = () => {
      try {
        const pendingReceipt = localStorage.getItem('pendingReceipt');
        if (pendingReceipt) {
          const receiptData = JSON.parse(pendingReceipt);
          if (receiptData.generatedHtml) {
            setReceiptPreview(receiptData.generatedHtml);
            setReceiptData(receiptData);
          }
        }
      } catch (error) {
        console.error('Error loading receipt preview:', error);
      }
    };

    loadReceiptPreview();
    
    // Also listen for storage changes for the receipt
    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === 'pendingReceipt') {
        loadReceiptPreview();
      }
    };

    window.addEventListener('storage', handleStorageChange);
    return () => window.removeEventListener('storage', handleStorageChange);
  }, []);

  // Add mobile-responsive watermark to receipt HTML
  const addWatermarkToReceipt = (html: string) => {
    const watermarkedHtml = `
      <div style="position: relative; display: inline-block; width: 100%; min-height: 400px;">
        <div style="
          max-width: 100%;
          overflow-x: auto;
          -webkit-overflow-scrolling: touch;
        ">
          ${html}
        </div>
        <div style="
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          pointer-events: none;
          z-index: 9999;
          background: repeating-linear-gradient(
            -45deg,
            transparent,
            transparent 20px,
            rgba(255, 0, 0, 0.03) 20px,
            rgba(255, 0, 0, 0.03) 40px
          );
        "></div>
        <div style="
          position: absolute;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%) rotate(-45deg);
          font-size: clamp(24px, 6vw, 48px);
          font-weight: 900;
          color: rgba(255, 0, 0, 0.12);
          pointer-events: none;
          z-index: 10000;
          white-space: nowrap;
          text-transform: uppercase;
          letter-spacing: 3px;
          text-shadow: 2px 2px 4px rgba(0,0,0,0.1);
          width: 100%;
          text-align: center;
        ">PREVIEW ONLY</div>
        <div style="
          position: absolute;
          bottom: 10px;
          left: 10px;
          background: rgba(0, 0, 0, 0.85);
          color: white;
          padding: 8px 12px;
          border-radius: 6px;
          font-size: 10px;
          font-weight: 500;
          pointer-events: none;
          z-index: 10000;
          backdrop-filter: blur(4px);
          max-width: calc(100% - 20px);
          box-sizing: border-box;
        ">Generated by HubReceipts.com - Not a valid receipt</div>
      </div>
    `;
    return watermarkedHtml;
  };

  // Make receipt HTML mobile responsive
  const makeReceiptMobileResponsive = (html: string) => {
    // Add mobile-responsive styles to the receipt HTML
    const mobileResponsiveHtml = html
      .replace(/width:\s*600px/g, 'width: 100%')
      .replace(/max-width:\s*600px/g, 'max-width: 100%')
      .replace(/width="600"/g, 'width="100%"')
      .replace(/style="([^"]*)"/g, (match: string, style: string) => {
        // Add responsive font sizes and padding
        let newStyle = style
          .replace(/font-size:\s*small/g, 'font-size: 14px')
          .replace(/font-size:\s*(\d+)px/g, (sizeMatch: string, size: string) => {
            const numericSize = parseInt(size);
            if (numericSize > 16) {
              return `font-size: clamp(14px, ${numericSize * 0.8}px, ${size}px)`;
            }
            return sizeMatch;
          })
          .replace(/padding:\s*(\d+)px/g, (paddingMatch: string, padding: string) => {
            const numericPadding = parseInt(padding);
            return `padding: clamp(8px, ${numericPadding * 0.6}px, ${padding}px)`;
          })
          .replace(/width:\s*(\d+)px/g, (widthMatch: string, width: string) => {
            const numericWidth = parseInt(width);
            if (numericWidth > 300) {
              return `width: 100%`;
            }
            return widthMatch;
          });
        
        // Ensure horizontal scrolling for tables on mobile
        if (style.includes('table') || style.includes('td') || style.includes('tr')) {
          newStyle += '; min-width: fit-content';
        }
        
        return `style="${newStyle}"`;
      });

    return mobileResponsiveHtml;
  };

  // Clear receipt preview
  const clearReceiptPreview = () => {
    localStorage.removeItem('pendingReceipt');
    setReceiptPreview(null);
    setReceiptData(null);
    setShowPreview(false);
  };

  // ✅ Handle checkout with proper authentication
  const handleCheckout = async (productId: string) => {
    try {
      setLoadingPlan(productId);

      // Double-check authentication before proceeding
      const userData = localStorage.getItem("user");
      const user = userData ? JSON.parse(userData) : null;
      const email = user?.email;

      if (!email) {
        alert('Please log in to proceed with checkout.');
        router.push("/register");
        return;
      }

      const response = await fetch('https://api.hubreceipts.com/api/payment/create-checkout-session', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ productId, email }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || `Checkout failed: ${response.status}`);
      }

      if (data.url) {
        window.location.href = data.url;
      } else {
        throw new Error('No checkout URL received from server');
      }
    } catch (err: any) {
      console.error('Checkout error:', err);
      
      if (err.message.includes('authentication') || err.message.includes('401')) {
        alert('Session expired. Please log in again.');
        router.push("/register");
      } else if (err.message.includes('400')) {
        alert('Invalid request. Please try again.');
      } else {
        alert(err.message || 'Something went wrong. Please try again.');
      }
    } finally {
      setLoadingPlan(null);
    }
  };

  const topRowPlans = [
    {
      id: '1-receipt',
      name: '1 Receipt',
      priceusd: 4.99,
      priceeur: 4.5,
      description: 'Perfect for trying out our generator.',
    },
    {
      id: '1-day',
      name: '1 Day Access',
      priceusd: 8.99,
      priceeur: 7.99,
      description: '24 hours of unlimited access.',
    },
    {
      id: '1-week',
      name: '1 Week Access',
      priceusd: 14.99,
      priceeur: 12.99,
      description: 'Ideal for short-term projects.',
    },
  ];

  const bottomRowPlans = [
    {
      id: '1-month',
      name: '1 Month',
      priceusd: 21.99,
      priceeur: 20.99,
      description: 'Best for regular business use.',
    },
    {
      id: '6-months',
      name: '6 Months',
      priceusd: 39.99,
      priceeur: 34.99,
      description: 'Maximum value for power users.',
    },
  ];

  const renderPlanCard = (plan: any) => (
    <div
      key={plan.id}
      className={`relative rounded-2xl border-2 bg-white transition-all duration-300 hover:shadow-xl hover:scale-[1.02] ${
        plan.popular ? 'border-yellow-400 shadow-lg' : 'border-gray-200 hover:border-blue-300'
      }`}
    >
      {/* Content */}
      <div className="p-6">
        <h2 className="text-2xl font-bold text-gray-900 mb-0">{plan.name}</h2>
        <p className="text-gray-600 mb-2 leading-relaxed">{plan.description}</p>

        <div className="flex items-baseline justify-center space-x-0 mb-0">
          <span className="text-4xl font-light text-gray-900">€{plan.priceeur}</span>
          <span style={{marginLeft:4}} className="text-2xl text-gray-400"> / </span>
          <span style={{marginLeft:6}} className="text-4xl font-light text-gray-900"> ${plan.priceusd}</span>
        </div>

        <p className="text-sm text-gray-500 text-center mb-2">One-time payment • No auto-renewal</p>

        <div className="mt-2">
          <button
            style={{background:'#0074d4'}}
            onClick={() => handleCheckout(plan.id)}
            disabled={loadingPlan === plan.id || !isLoggedIn}
            className="w-full bg-gradient-to-r hover:from-blue-700 hover:to-blue-800 disabled:from-gray-400 disabled:to-gray-500 text-white font-semibold py-3 px-0 transition-all duration-300 transform hover:shadow-lg disabled:shadow-none disabled:cursor-not-allowed flex items-center justify-center rounded-lg"
          >
            {!isLoggedIn ? (
              <>
                <ShoppingCart size={18} />
                Login to Purchase
              </>
            ) : loadingPlan === plan.id ? (
              <>
                <div className="animate-spin rounded-full h-2 w-2 border-0 border-white border-t-transparent"></div>
                Redirecting...
              </>
            ) : (
              <>
                <span style={{color:'white'}}>
                  Pay with Apple Pay + 3
                </span>
              </>
            )}
          </button>
          
          {!isLoggedIn && (
            <p className="mt-3 text-xs text-red-600 text-center font-medium">
              Please log in to purchase
            </p>
          )}
        </div>
      </div>
    </div>
  );

  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-slate-50 to-blue-50">
      <Header />
      
      {/* Mobile-Responsive Receipt Preview Modal */}
      {showPreview && receiptPreview && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-2 sm:p-4">
          <div className="bg-white rounded-2xl w-full max-w-full sm:max-w-5xl max-h-[95vh] overflow-hidden shadow-2xl border border-gray-200 mx-2 sm:mx-0">
            <div className="flex justify-between items-center p-4 sm:p-6 border-b border-gray-200 bg-gradient-to-r from-blue-50 to-indigo-50">
              <div className="flex-1 min-w-0">
                <h2 className="text-lg sm:text-2xl font-bold text-gray-900 truncate">Receipt Preview</h2>
                <p className="text-gray-600 mt-1 text-sm sm:text-base hidden sm:block">
                  Your generated receipt is ready to download
                </p>
              </div>
              <div className="flex gap-2 sm:gap-3 flex-shrink-0">
                <button
                  onClick={clearReceiptPreview}
                  className="px-3 sm:px-5 py-2 sm:py-2.5 bg-gradient-to-r from-gray-500 to-gray-600 text-white rounded-lg sm:rounded-xl hover:from-gray-600 hover:to-gray-700 transition-colors flex items-center gap-1 sm:gap-2 font-semibold text-sm sm:text-base"
                >
                  <X size={16} className="sm:w-5 sm:h-5" />
                  <span className="hidden sm:inline">Close</span>
                </button>
              </div>
            </div>
            <div className="p-2 sm:p-6 overflow-auto max-h-[calc(95vh-80px)] bg-gray-50">
              {/* Mobile Warning Banner */}
              <div className="bg-yellow-50 border border-yellow-200 rounded-lg sm:rounded-xl p-3 sm:p-4 mb-4 sm:mb-6">
                <div className="flex items-start gap-2 sm:gap-3">
                  <div className="text-yellow-600 flex-shrink-0 mt-0.5">
                    <Eye size={18} className="sm:w-5 sm:h-5" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <h4 className="font-semibold text-yellow-800 text-sm sm:text-base">Preview Mode</h4>
                    <p className="text-yellow-700 text-xs sm:text-sm">
                      It looks bad the receipt in the browser, but once it's sent via email looks legit haha.
                      <span className="block sm:hidden mt-1">Scroll horizontally to view full receipt </span>
                    </p>
                  </div>
                </div>
              </div>
              
              {/* Receipt Container with Horizontal Scroll on Mobile */}
              <div className="bg-white rounded-lg sm:rounded-xl border-2 border-blue-100 shadow-inner overflow-hidden">
                <div 
                  dangerouslySetInnerHTML={{ 
                    __html: addWatermarkToReceipt(makeReceiptMobileResponsive(receiptPreview)) 
                  }}
                  className="receipt-preview p-3 sm:p-6 min-w-0"
                  style={{
                    WebkitOverflowScrolling: 'touch',
                    overflowX: 'auto'
                  }}
                />
              </div>
              
              {/* Call to Action Section */}
              <div className="text-center mt-4 sm:mt-8 bg-white rounded-lg sm:rounded-2xl p-4 sm:p-8 border-2 border-dashed border-green-200">
                <h3 className="text-lg sm:text-2xl font-bold text-gray-900 mb-2 sm:mb-4">Ready to send the receipt to your email?</h3>
                <p className="text-gray-600 mb-4 sm:mb-6 text-sm sm:text-lg max-w-md mx-auto">
                  Purchase any plan to download this receipt without watermarks and get full access to our receipt generator.
                </p>
                <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center items-center">
                  <button
                    onClick={() => {
                      setShowPreview(false);
                      document.getElementById('pricing-plans')?.scrollIntoView({ behavior: 'smooth' });
                    }}
                    className="bg-gradient-to-r from-green-600 to-emerald-600 text-white px-4 sm:px-8 py-3 sm:py-4 rounded-lg sm:rounded-xl hover:from-green-700 hover:to-emerald-700 transition-all duration-300 transform hover:scale-105 flex items-center gap-2 sm:gap-3 font-bold text-base sm:text-lg shadow-lg w-full sm:w-auto justify-center"
                  >
                    Choose Plan
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Mobile-Responsive Receipt Preview Banner */}
      {receiptPreview && !showPreview && (
        <div className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white py-3 sm:py-2 px-3 sm:px-5 shadow-lg">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between max-w-7xl mx-auto gap-3 sm:gap-0">
            <div className="flex items-center gap-3">
              <div className="flex-1 min-w-0">
                <h3 className="text-lg sm:text-xl font-bold truncate">Your Receipt is Ready! 🎉</h3>
                <p className="text-blue-100 mt-1 text-sm hidden sm:block">
                  Preview your generated receipt and purchase to download the clean version
                </p>
              </div>
            </div>
            <div className="flex gap-2 sm:gap-3 justify-end">
              <button 
                onClick={() => setShowPreview(true)}
                className="bg-white text-blue-600 px-4 sm:px-6 py-2 sm:py-3 rounded-lg sm:rounded-xl hover:bg-blue-50 transition-all duration-300 transform hover:scale-105 flex items-center gap-2 font-bold shadow-lg text-sm sm:text-base flex-1 sm:flex-none justify-center"
              >
                <Eye size={16} className="sm:w-5 sm:h-5" />
                View Preview
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Authentication Status Banner */}
      {!isLoggedIn && !receiptPreview && (
        <div className="bg-gradient-to-r from-amber-500 to-orange-500 text-white py-3 px-4 text-center">
          <p className="text-sm font-medium">
            Please <button onClick={() => router.push("/register")} className="underline font-bold bg-white/20 px-2 py-1 rounded">log in</button> to purchase a plan
          </p>
        </div>
      )}

      {/* Main Content */}
      <div style={{marginTop:10}} className="flex-1">
        {/* Top Row Plans */}
        <section id="pricing-plans" className="mx-auto w-full max-w-6xl px-2 sm:px-2 pb-2">
          <div className="grid gap-2 sm:gap-2 lg:grid-cols-3">
            {topRowPlans.map(renderPlanCard)}
          </div>
        </section>

        {/* Bottom Row Plans */}
        <section className="mx-auto w-full max-w-4xl px-2 sm:px-6 pb-20">
          <div className="grid gap-4 sm:gap-8 lg:grid-cols-2">
            {bottomRowPlans.map(renderPlanCard)}
          </div>
        </section>
      </div>

      <Footer />
    </div>
  );
}